#!/bin/bash
# try run `echo '{"version": "1.0"}' | $0 2> api.log | cat`

exec 3>&1
exec 1>&2

payload=$(mktemp /tmp/payload.XXXXXX)

# in
cat > $payload <&0

echo DEBUG: script file check
echo DEBUG: number of arguments $#
echo DEBUG: arguments $@
echo DEBUG: whoami $(whoami)
echo DEBUG: whereami $(pwd)
echo DEBUG: request payload file $payload
echo DEBUG: request payload content:

jq -r '.' < $payload

version=$( jq -r '.version // "unknown"' < $payload )
echo DEBUG: version $version

# impl
# TODO generate new version

# out
echo DEBUG: response content:

jq -n '[
  {ver: "0"}
]' 

jq -n '[
  {ver: "0"}
]' >&3
