#!/bin/bash
# try run `echo '{"version": "1.0"}' | $0 2> api.log | cat`

exec 3>&1
exec 1>&2

payload=$(mktemp /tmp/payload.XXXXXX)

# in
cat > $payload <&0

echo DEBUG: script file in
echo DEBUG: number of arguments $#
echo DEBUG: arguments $@
echo DEBUG: whoami $(whoami)
echo DEBUG: whereami $(pwd)
echo DEBUG: env $(env)
echo DEBUG: request payload file $payload
echo DEBUG: request payload content:

jq -r '.' < $payload

version=$( jq -r '.version // "unknown"' < $payload )
echo DEBUG: version $version

# impl
# TODO use something to update the folder $1
ver=$(echo $version | jq -r '.ver')
echo DEBUG: ver $ver
touch $1/$ver
ls $1

# out
echo DEBUG: response content:

jq -n '{
  version: {ver: "'$ver'"},
  metadata: [
    { name: "script", value: "in" },
    { name: "in", value: "in" }
  ]
}'

jq -n '{
  version: {ver: "'$ver'"},
  metadata: [
    { name: "script", value: "in" },
    { name: "in", value: "in" }
  ]
}' >&3
