#!/bin/bash
# try run `echo '{"version": "1.0"}' | $0 2> api.log | cat`

exec 3>&1
exec 1>&2

payload=$(mktemp /tmp/payload.XXXXXX)

# in
cat > $payload <&0

echo DEBUG: script file out
echo DEBUG: number of arguments $#
echo DEBUG: arguments $@
echo DEBUG: whoami $(whoami)
echo DEBUG: whereami $(pwd)
echo DEBUG: env $(env)
echo DEBUG: request payload file $payload
echo DEBUG: request payload content:

jq -r '.' < $payload

# impl
# TODO use the folder $1 to update something
ls $1

# out
echo DEBUG: response payload content:

jq -n '{
  version: {ver: "2"},
  metadata: [
    { name: "script", value: "out" },
    { name: "out", value: "out" }
  ]
}'

jq -n '{
  version: {ver: "2"},
  metadata: [
    { name: "script", value: "out" },
    { name: "out", value: "out" }
  ]
}' >&3
